api_platform:
    title: Restaurant API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 10
    path_segment_name_generator: api_platform.path_segment_name_generator.underscore
    collection:
        pagination:
            enabled: true
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
        swagger_ui_extra_configuration:
            display_operation_id: true
            defaultModelsExpandDepth: -1  # This hides the schemas section
